Added exclude option to update action

diff --git a/tvjobs b/tvjobs
--- a/tvjobs
+++ b/tvjobs
@@ -14,19 +14,24 @@ show_usage() {
 	echo "  ~/.tvscraperrc" >&2
 	echo "" >&2
 	echo "Valid ACTION" >&2
-	echo "  update [only_season|only_show]" >&2
+	echo "  update [additional options...]" >&2
 	echo "  notify" >&2
 	echo "  cleanup" >&2
 	echo "  get-best [additional options...]" >&2
 	echo "  find-missing [additional options...]" >&2
 	echo "" >&2
 	echo "Some ACTIONs have additional options:" >&2
+	echo "  update" >&2
+	echo "    -x <exclude_filter> comma-separated list of scrapers to exclude, in the" >&2
+	echo "                        following format: <source:type>[,<source:type>...]" >&2
+	echo "                        type can be show or season, '*' considered wildcard" >&2
+	echo "                        E.g: -x wikipedia:season,DDU:*,*:show ">&2
 	echo "  get-best" >&2
-	echo "    -t <ed2k|torrent> filter link by type" >&2
-	echo "    -d <seconds>      return only links published in the last X seconds" >&2
+	echo "    -t <ed2k|torrent>   filter link by type" >&2
+	echo "    -d <seconds>        return only links published in the last X seconds" >&2
 	echo "  find-missing" >&2
-	echo "    -d <seconds>      return episode missing files only if episode was" >&2
-	echo "                      aired before <seconds> ago">&2
+	echo "    -d <seconds>        return episode missing files only if episode was" >&2
+	echo "                        aired before <seconds> ago">&2
 }
 
 
@@ -81,15 +86,48 @@ api() {
 }
 
 do_update() {
-	filter="$1"
+
+	excludeFilter=""	
+	legacyFilter=""
+	while [ $# -gt 0 ]; do
+		case "$1" in
+			-x) shift ; excludeFilter="$1" ;;
+			-*) 
+				echo "Unknown option $1" >&2
+				show_usage
+				exit 1
+				;;
+			only_season)
+				legacyFilter="*:show" 
+				echo "WARNING: only_season is deprecated. Use option '-x *:show' instead." >&2
+				;;
+			only_show)
+				legacyFilter="*:season" 
+				echo "WARNING: only_show is deprecated. Use option '-x *:season' instead." >&2
+				;;
+			*)  break;;	# terminate while loop
+		esac
+		shift
+	done
+
+	if ! [ -z "$legacyFilter" ]; then
+		if [ -z "$excludeFilter" ]; then
+			excludeFilter="$legacyFilter";
+		else
+			excludeFilter="$excludeFilter,$legacyFilter";
+		fi
+	fi
+
 	scraperList=$(api getActiveScrapers | awk '
 		doRead=="id" { id=$2; doRead="nothing"; }
 		doRead=="uri" { uri=$2; doRead="nothing"; }
 		doRead=="season" { season=$2; doRead="nothing"; }
+		doRead=="source" { source=$2; doRead="nothing"; }
 		/^      \["id"\]/ { doRead="id"; }
 		/^      \["uri"\]/ { doRead="uri"; }
 		/^      \["season"\]/ { doRead="season"; }
-		/^    \}/ { printf "%s,%s,%s\n", id, uri, season; }
+		/^      \["source"\]/ { doRead="source"; }
+		/^    \}/ { printf "%s,%s,%s,%s\n", id, uri, season, source; }
 	')
 
 	oldIFS=$IFS
@@ -101,14 +139,33 @@ do_update() {
 			scraperId=$(echo $scraperData | cut -d , -f 1 | sed s/\"//g)
 			scraperUri=$(echo $scraperData | cut -d , -f 2 | sed s/\"//g)
 			scraperSeason=$(echo $scraperData | cut -d , -f 3 | sed s/\"//g)
-			[ "$filter" == "only_season" ] && [ -z "$scraperSeason" ] && continue
-			[ "$filter" == "only_show" ] && ! [ -z "$scraperSeason" ] && continue
-			echo -n "Running scraper $scraperId ($scraperUri) ..."
-			scraperOutput=$(api runScraper scraperId $scraperId)
-			if [ $? -eq 0 ]; then
-				echo "OK."
-			else
-				echo "Failed!"
+			scraperSource=$(echo $scraperData | cut -d , -f 4 | sed s/\"//g)
+
+			skipScraper=0
+			IFS=","
+			for x in $excludeFilter; do
+				IFS=$oldIFS
+				xSource=$(echo "$x" | cut -d : -f 1)
+				xType=$(echo "$x" | cut -d : -f 2)
+
+				if [ "$xSource" == "*" ] || [ "$xSource" == "$scraperSource" ] ; then
+					[ "$xType" == "*" ] && skipScraper=1 && break;
+					[ "$xType" == "season" ] && ! [ -z "$scraperSeason" ] && skipScraper=1 && break;
+					[ "$xType" == "show" ] && [ -z "$scraperSeason" ] && skipScraper=1 && break;
+				fi
+			done
+			IFS=$oldIFS
+
+			if [ "$skipScraper" -gt 0 ]; then
+				echo "Skipping scraper $scraperId ($scraperUri)"
+			else 
+				echo -n "Running scraper $scraperId ($scraperUri) ..."
+				scraperOutput=$(api runScraper scraperId $scraperId)
+				if [ $? -eq 0 ]; then
+					echo "OK."
+				else
+					echo "Failed!"
+				fi
 			fi
 		done
 	fi
